# Main configuration
project_root: "."
week_pattern: "*[0-9][0-9][0-9][0-9]Week[0-9][0-9]"

# Path configuration
paths:
  input_dir: "data/input"
  parsed_dir: "data/parsed"
  audio_tts_dir: "data/audio_tts"
  audio_rvc_dir: "data/audio_rvc"
  captions_dir: "data/captions"
  videos_dir: "data/videos"
  
  # Assets
  assets_dir: "assets"
  hubert_dir: "assets/hubert"
  rmvpe_dir: "assets/rmvpe"
  rvc_models_dir: "assets/rvc_models"
  tts_models_dir: "assets/tts_models"
  video_resources_dir: "assets/video_resources"

# Content parsing
parsing:
  timeout_sec: 20
  retries: 2
  user_agent: "Mozilla/5.0 (compatible; FinancialVideoPipeline/1.0)"
  enable_html_scrape: true
  sections_subdir: "sections"
  images_subdir: "images"

# Text-to-speech
tts:
  engine: "edge"  # Choose: edge | piper (alias: default_tts)
  # Edge TTS voice name; example below is a common US-English voice
  default_voice: "en-US-ChristopherNeural"
  length_scale: 1
  sentence_silence: 0.0  # Set this to 0.0 to avoid double pauses, since the code is implemented based on sentence per piper call, and assemble the audio later per txt file
  sentence_pause: 0.6     # Additional pause between sentences in SRT timing
  piper_extra_args: []
  text_extensions: [".txt"]
  # Sentence-based generation (more accurate timing)
  sentence_based_generation: true

# RVC voice conversion
rvc:
  checkpoint_name: "Formal_e130_s58890.pth"
  checkpoint_prefix: "Formal"
  f0_method: "rmvpe"
  rms_mix_rate: 0.25
  protect: 0.33
  filter_radius: 3
  wav_extensions: ["*.wav", "*.WAV"]
  rvc_project_path: "./src/financial_video_pipeline/rvc/"

# Caption generation
caption:
  model_size: "base"
  device: "auto"
  compute_type: "float32"  # Use float32 for CPU compatibility
  language: "en"
  beam_size: 5

# Video assembly
video:
  resolution: "1920x1080"
  fps: 30
  video_codec: "libx264"
  audio_codec: "aac"
  crf: 23
  preset: "medium"
  
  # Output settings
  save_intermediate_videos: false  # only save final video
  
  # Image handling
  resize_images: true  # Resize images to target resolution
  resize_method: "pad"  # "pad" (black bars) or "stretch" (distort) or "crop" (crop to fit)
  
  # Caption styling
  caption_font: "Arial"
  caption_font_size: 10
  caption_font_color: "white"
  caption_outline_color: "black"
  caption_outline_width: 1
  caption_position: "bottom"  # "top", "bottom", "center"
  
  # Video resources
  start_video_dir: "assets/video_resources/start"
  end_video_dir: "assets/video_resources/end"
  transition_image_dir: "assets/video_resources/transition"
  logo_path: "assets/video_resources/logo/logo.png"
  
  # Logo/watermark settings
  logo_size: 100  # Logo size in pixels (will be resized to square)
  logo_position: "bottom-right"  # "top-left", "top-right", "bottom-left", "bottom-right"
  logo_padding: 20  # Padding from video edges in pixels
  
  # Transition settings
  transition_duration: 3.0  # seconds
  transition_font: "Arial"
  transition_font_size: 84
  transition_font_color: "white"
  transition_outline_color: "black"
  transition_outline_width: 10